name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg DB_PSWD=${{ secrets.DB_PASSWORD }} \
            -t ${{ secrets.DOCKER_USERNAME }}/test_backend_erp:latest .

      # 4. Push Docker image to DockerHub
      # - name: Push Docker image
      #   run: |
      #     docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
      # - name: Execute commands via SSH
      #   uses: appleboy/ssh-action@v0.1.8
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     script: |
      #       echo "Conectando al servidor remoto..."
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/my-image:latest
      #       docker stop my-container || true
      #       docker rm my-container || true
      #       docker run -d --name my-container ${{ secrets.DOCKER_USERNAME }}/my-image:latest

